### ISSUE TITLE
New features / enhancements

### ISSUE THREAD

**Issue by daniel-luberda** [luberda-molinet/FFImageLoading#859]
- [ ] Memory cache - Image Pinning to prevent eviction of specific images - https://github.com/luberda-molinet/FFImageLoading/issues/381
- [ ] Include transformations in base package (obsolete Xamarin.FFImageLoading.Transformations package) - https://github.com/luberda-molinet/FFImageLoading/issues/433
- [ ] More verbose logging - https://github.com/luberda-molinet/FFImageLoading/issues/443
- [ ] ErrorPlaceholder, LoadingPlaceholder loading from Stream support   -https://github.com/luberda-molinet/FFImageLoading/issues/473
- [ ] Add max disk cache size restrictions - https://github.com/luberda-molinet/FFImageLoading/issues/500
- [ ] IMD5Helper implementation refactor - https://github.com/luberda-molinet/FFImageLoading/issues/677
- [ ] Number of repeats to GIF image - https://github.com/luberda-molinet/FFImageLoading/issues/718
- [ ] SVG with xlink:href not rendering external image  https://github.com/luberda-molinet/FFImageLoading/issues/750
- [ ] Improve work scheduler in slow internet connection scenarios  - https://github.com/luberda-molinet/FFImageLoading/issues/766

**Comment by EmilAlipiev** [comment]
I am not sure if it is related "Improve work scheduler in slow internet connection scenarios"  but this is quite important for me also. when i am on slow connection, Errorplaceholder sometimes appears too late. I couldnt figure out a proper timeout to handle this. I have already code as below, using below configuration, I expected 5 secs timeout but it didnt seem to work for me.

 var config = new FFImageLoading.Config.Configuration()
            {
                //FadeAnimationDuration = 250,
                //FadeAnimationForCachedImages = true,
                //FadeAnimationEnabled = true,
                HttpHeadersTimeout = 5,
                HttpReadTimeout = 5,
                MaxMemoryCacheSize = 50 * 1024 * 1024
            };
