### ISSUE TITLE
Xamarin.Forms enhancements

### ISSUE THREAD

**Issue by daniel-luberda** [luberda-molinet/FFImageLoading#860]
- [ ] Bindable transformations properties - https://github.com/luberda-molinet/FFImageLoading/issues/499
- [ ] XAML Previewer support - https://github.com/luberda-molinet/FFImageLoading/issues/418
- [ ] Add CachedButton implementation - https://github.com/luberda-molinet/FFImageLoading/issues/850

**Comment by mzhukovs** [comment]
Still no bindable transformation properties?  :((

**Comment by LeoJHarris** [comment]
Same here, really like to see binding on transformations :) this will be very beneficial to developers! 👍

**Comment by begreal** [comment]
still not bindable...

**Comment by LittleBoxOfChicken** [comment]
Does anybody have a workaround for this issue?

**Comment by zdanovs** [comment]
> Does anybody have a workaround for the issue regarding bindings?

https://github.com/luberda-molinet/FFImageLoading/issues/491#issuecomment-279891483

**Comment by LittleBoxOfChicken** [comment]
> > Does anybody have a workaround for the issue regarding bindings?
> 
> [#491 (comment)](https://github.com/luberda-molinet/FFImageLoading/issues/491#issuecomment-279891483)

I found it as well, my apologies for not linking it in this issue.

Thank you for the link. This workaround worked for me.

**Comment by richigarza** [comment]
I will comment every week until transformations can be bindable.
Jaja just kidding.

**Comment by mos379** [comment]
still not bindable Color? :)
